{% set version = "1.22" %}

package:
  name: leveldb
  version: "{{ version }}" # without quote, yaml.load() drops 0

source:
  fn: leveldb-{{ version }}.tar.gz
  url: https://github.com/google/leveldb/archive/{{ version }}.tar.gz
  sha256: 55423cac9e3306f4a9502c738a001e4a339d1a38ffbee7572d4a07d5d63949b2
  patches:
    # - 0001-Windows-port-from-bitcoin-core.patch
    # - 0002-Fix-MSVC-errors.patch
    # - 0003-Relax-tests-on-Windows.patch

build:
  number: 0
  run_exports:
    # last two version had incompatibilities in minor version
    # https://abi-laboratory.pro/tracker/timeline/leveldb/
    - {{ pin_subpackage('leveldb', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake >3.4
    - snappy
    - msinttypes    # [win and py<35]
  run:
    - snappy

test:
  commands:
    # - test -f ${PREFIX}/lib/libleveldb.a                 # [unix]
    - test -f ${PREFIX}/lib/libleveldb.dylib            # [osx]
    - test -f ${PREFIX}/lib/libleveldb.so               # [linux]
    - if not exist %LIBRARY_BIN%\\leveldb.dll exit 1    # [win]

about:
  home: https://github.com/google/leveldb
  license: BSD
  summary: A fast key-value storage library providing ordered mappings.
  description: |
    LevelDB supports arbitrary byte arrays as both keys and values, singular get,
    put and delete operations, batched put and delete, bi-directional iterators
    and simple compression using the very fast Snappy algorithm.
  doc_url: https://github.com/google/leveldb/tree/master/doc
  doc_source_url: https://github.com/google/leveldb/blob/master/doc/index.md
  dev_url: https://github.com/google/leveldb

extra:
  recipe-maintainers:
    - jakirkham
