travis:
  secure:
    BINSTAR_TOKEN: wL8Vzyq4g/19xJtYu5DMlDbbK6xGwQX8J3UE/kk9feQWsyA+8rbNsjZc9es86t1u09MUVD4s/u+iOZr5XUstIFAcYk5ziUmWbN/FdNAKChBHFxMOW3ZiIm3DRZA6SyKL6ubcFaGYRy91rZQA8Gy8zlkIw3XgEVSU8jBtRXUBS6HuK7VkhuBgLDdX7hmc6Ym7WMbIQ4y1LpJWLjsaAASeqK3rphdv7+lLai+jabhNA5vKNN99bKne3iFJxxWcHUsdQRYYORmpxAig3TCq13DS2+WrR8UZTpiiFQibAlGOvZe5xeAT2o0ezHEuE6Ouihx+OYIl3ra1x378t3S01KihuiRatfCS+kuTDjj9+x+4Ht9b3vtCIc+QxxpZVCe9CxkmYg1Z23zYKsMeoJ/1wsAMpsBcDjHNRH5Ex23udzIW8OuS7cVgrcWJ9H0UdeREli2gQHIPH5EZSYqDGrwf510HXGgRUs8g4152gKsuCjqLTcKu25auXqj722ErEXy52zucbCsPLQBFQDTJK+BVjb4qrcWezNhYvLUJUKSc7V2a0+Z7M9BHzyqJnhh1TMKVYzoC2N6L9jy33mJg79FBWDKWsAph2NaTi7qlPLIwqJ2DeA76GfsIsZJaFUCtpeVKp7s6JHtD1Q0B1dgMACZOtDNWB3uaNbKMWU8JN28QDb1uUCo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
