travis:
  secure:
    BINSTAR_TOKEN: KFo2s3mqZ5B5twdruY0Q00z46Uy7jDpbB+JiHHXmbLW8nRT6RPabTb8ve9VBtRjxvIRCXmvYo7Isov/lAJVZrry7H7ppD8I7tjLsoXS67CLiY24Tv732GKMPLXiwNxafn1UwoAqyxiviPBNVVAecIZ7GXiOPJ/DpWG78ZwMK+nhxwlc40fmS8HuJvrytmAlInXDA6NafTZnY9fQqHjqYLI3KHaXJYyCQmpDJvsSnmJcaYWV4UZwGOFQUhLT1cViduQupF2U+mOblfItxqTtI2srQcocOOZWxTHSroNUXghf5JsTfnaoBZ0RSDJGCqw26S+mIHnokNuvbgmBN/6MU0ogtOAFJMquFlesWKE1k5RA/0BzYvBRG3Z/+Z7XKu00VGJtTF3iG9uQ9BeCDAXdeBjXi9vB2QLNYiFXt/fIgpo61NKhjQSg+5sGEVH0Awr+ThWGFJS86HU/ROXeorfib3NVCK8PjSAuFbM92bdDVNFqKUG9c3oK1xis0KYa8+C96aD4kAZvdOVjViLMYIL9M3LVDLIdOVBgWDqN//4AZlpl54WkxN2ZItnWLZLMggKAhWW7Mc/GBLTR/flNaXy6TaAQJk6KsnjAjJPjc2mw1Re914EoF34s9tALx9nheLkZrIvrLLozP0f3rqX1tktvQLZTttUpJc7MZin/dvp4wKa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
